apiVersion: apps/v1
kind: Deployment
metadata:
  name: sycamore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sycamore-api
  template:
    metadata:
      labels:
        app: sycamore-api
    spec:
      containers:
        - name: api
          image: node:18-alpine
          command:
            - node
            - -e
            - |
              const http = require("http");
              const port = process.env.PORT || 3000;

              const server = http.createServer((req, res) => {
                if (req.url === "/healthz") {
                  res.writeHead(200);
                  return res.end("ok");
                }
                res.writeHead(200);
                res.end("sycamore-api running");
              });
              server.listen(port, () => console.log("listening on", port));
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
